kafka:
  bootstrap.servers: ${KAFI_KAFKA_SERVER}
  security.protocol: sasl_plaintext
  sasl.mechanisms: SCRAM-SHA-256
  sasl.username: ${KAFI_KAFKA_USERNAME}
  sasl.password: ${KAFI_KAFKA_PASSWORD}

kafi:
  flush.num.messages: 10000
  flush.timeout: -1
  retention.ms: -1
  consume.timeout: 5.0
  consume.batch.size: 1 
  enable.auto.commit: true
  session.timeout.ms: 10000
  block.num.retries.int: 50
  block.interval: 0.1
  auto.offset.reset: earliest
  progress.num.messages: 1000
